---
# not check `COMPLIANCE030206` by ansible-lint
# Post Check hostname
#


  - name: wait for connection 1
    wait_for_connection:
      delay: 60
      sleep: 10
      timeout: 300
    when: VAR_NEC_WIN_hostname_reboot

  - debug:
      msg: "NEC_WIN_reboot_required: {{ NEC_WIN_reboot_required }}"
    tags:
      - skip_ansible_lint
# - name: wait for connection 2
  # wait_for_connection:
    # delay: 10
    # timeout: 300
  # when: VAR_NEC_WIN_hostname_reboot

  - name: post check hostname
    win_shell: Write-Host -NoNewline (hostname)
    register: ret_post_name
    failed_when: ret_post_name.stdout != VAR_NEC_WIN_hostname
    when:
      - ret_pre_name | changed
      - ret_name_change_1 | changed or ret_name_change_2 | changed or ret_name_change_3 | changed
      - VAR_NEC_WIN_hostname_reboot
    check_mode: no

  - name: post check type when new type is "domain"
    win_shell: (Get-WmiObject -Class Win32_ComputerSystem).Domain
    register: ret_post_type_value
    failed_when: ret_post_type_value.stdout_lines.0.lower() != VAR_NEC_WIN_hostname_domain.name.lower()
    when:
      - ret_type_change_3 | changed or ret_type_change_4 | changed
      - ret_pre_type_value | changed
      - VAR_NEC_WIN_hostname_reboot
      - VAR_NEC_WIN_hostname_type.lower() == "domain"
    check_mode: no

  - name: post check type when new type is "workgroup"
    win_shell: (Get-WmiObject -Class Win32_ComputerSystem).Domain
    register: ret_post_type_value
    failed_when: ret_post_type_value.stdout_lines.0.lower() != VAR_NEC_WIN_hostname_workgroup.lower()
    when:
      - ret_type_change_1 | changed or ret_type_change_2 | changed
      - ret_pre_type_value | changed
      - VAR_NEC_WIN_hostname_reboot
      - VAR_NEC_WIN_hostname_type.lower() == "workgroup"
    check_mode: no
