---
# not check `COMPLIANCE020201` by ansible-lint
# not check `COMPLIANCE030206` by ansible-lint
- name: set WIN_reboot_required
  set_fact:
    WIN_reboot_required: "{{ WIN_reboot_required | d(false) }}"

- name: check param VAR_WIN_AdminApprovalMode_EnableLUA none
  fail:
    msg: "The variable VAR_WIN_AdminApprovalMode_EnableLUA cannot be NULL."
  when: "(VAR_WIN_AdminApprovalMode_EnableLUA is none) or (VAR_WIN_AdminApprovalMode_EnableLUA == '')"

- name: check param VAR_WIN_AdminApprovalMode_EnableLUA type
  fail:
    msg: "The variable VAR_WIN_AdminApprovalMode_EnableLUA must be bool type."
  when:
    - VAR_WIN_AdminApprovalMode_EnableLUA != True
    - VAR_WIN_AdminApprovalMode_EnableLUA != False

- name: run All Administrators in Admin Approval Mode
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    type: dword
    data: "{{ (VAR_WIN_AdminApprovalMode_EnableLUA == True) | ternary('1','0') }}"
  register: reg_state

- name: notify handlers
  set_fact:
  changed_when: true
  notify:
    - Run reboot command
    - Wait for connection down
    - Wait for connection up
  when:
    - reg_state is changed
    - VAR_WIN_AdminApprovalMode_reboot == true

- name: fulsh handlers
  meta: flush_handlers

- name: debug reboot message
  debug:
    msg: "Restart now: {{ VAR_WIN_AdminApprovalMode_reboot }}"
  tags:
    - skip_ansible_lint

- name: changed required value
  set_fact:
    WIN_reboot_required: "{{ not VAR_WIN_AdminApprovalMode_reboot }}"
  when: reg_state is changed