---
#
# tasks file for interface
#

  - import_tasks: pre_check.yml

# disable or enable interface
  - include_tasks: modify_1.yml
    with_items: "{{ interface_ret.results }}"
    loop_control:
      loop_var: pre_results
    when: pre_results | changed

  # - debug:
      # msg: "{{ interface_ret.results }}"

  # change interface settings
  - include_tasks: modify_2.yml
    with_items: "{{ static_ret_pre.results }}"
    loop_control:
      loop_var: settings
    when: settings | changed

  - include_tasks: modify_3.yml