---
# not check `COMPLIANCE020201` by ansible-lint
# not check `COMPLIANCE030206` by ansible-lint
#modify

  - name: modify pagefile registry value
    raw: Set-ItemProperty '{{ location }}' 'PagingFiles' -Value '{{ data }}' -Type 'MultiString'
    when: pre_reg_val | changed

  - name: notify handlers
    set_fact:
    changed_when: true
    notify:
      - Run reboot command
      - Wait for connection down
      - Wait for connection up
    when:
      - pre_reg_val | changed
      - VAR_NEC_WIN_virtual_memory_reboot == true

  - meta: flush_handlers

  - debug:
      msg: "required: {{ NEC_WIN_reboot_required }}"
    tags:
      - skip_ansible_lint

  - name: changed required value
    set_fact:
      NEC_WIN_reboot_required: "{{ not VAR_NEC_WIN_virtual_memory_reboot }}"
    when: pre_reg_val | changed

  - debug:
      msg: "required: {{ NEC_WIN_reboot_required }}"
    tags:
        - skip_ansible_lint