---
#
# change interface
#
# nic state : up
  - name: (pre nic state is up)set nic state disabled
    win_shell: Disable-NetAdapter -Name "{{ pre_results.item.name }}" -Confirm:$false
    register: result1
    when:
      - pre_results.item.state is defined
      - pre_results.item.state.lower() == "disabled"

  - name: (pre nic state is disabled)set nic state up
    win_shell: Enable-NetAdapter -Name "{{ pre_results.item.name }}" -Confirm:$false
    register: result2
    when:
      - pre_results.item.state is defined
      - pre_results.item.state.lower() == "up"

  - name: sleep for 5 seconds and continue with play
    wait_for_connection:
        delay: 5
    delegate_to: 127.0.0.1
    when: (result1 is changed) or (result2 is changed)

