---
#
# change interface
#
# IP: change static ip address
  - name: delete static ip address
    win_shell: Remove-NetIPAddress -InterfaceAlias "{{ settings.item.name }}" -AddressFamily IPv4 -Confirm:$False

  - name: disable nic state
    win_shell: Disable-NetAdapter -Name "{{ settings.item.name }}" -Confirm:$false
    changed_when: true

  - name: enable nic state
    win_shell: Enable-NetAdapter -Name "{{ settings.item.name }}" -Confirm:$false
    changed_when: true

  - name: new static ip address
    win_shell: New-NetIPAddress -InterfaceAlias "{{ settings.item.name }}" -AddressFamily IPv4 -IPAddress "{{ settings.item.ipaddresses.0.ip }}" -PrefixLength "{{ settings.item.ipaddresses.0.prefix }}" -Confirm:$False

  - name: set gateway
    win_shell: (Get-WMIObject -Class Win32_NetworkAdapterConfiguration | Where-Object {$_.InterfaceIndex -eq (Get-NetIPAddress -InterfaceAlias "{{ settings.item.name }}" -AddressFamily IPv4).ifIndex}).SetGateways("{{ settings.item.ipaddresses.0.gateway }}")
