---
  - name: get Autoupdate's available options
    set_fact:
        AVAILABLE_STATUS_LIST: ["NOTCONFIGURED","ENABLED","DISABLED"]
  - name: get available switch options
    set_fact:
        AVAILABLE_SWITCH_LIST: ["ENABLED","DISABLED"]
  - name: check whether VAR_NEC_WIN_update_AU is legal or not
    block:
      - name: check whether status is legal or not
        fail:
            msg: status' value is unavailable
        when:
          - VAR_NEC_WIN_update_AU.status is defined
          - ((VAR_NEC_WIN_update_AU.status is none) or (VAR_NEC_WIN_update_AU.status == "")
            or (not VAR_NEC_WIN_update_AU.status.strip().upper() in AVAILABLE_STATUS_LIST))

      - name: check other items of VAR_NEC_WIN_update_AU when status is ENABLED
        block:
          - name: check automaticMaintenanceEnabled
            fail:
                msg: automaticMaintenanceEnabled' value is unavailable
            when:
              - VAR_NEC_WIN_update_AU.automaticMaintenanceEnabled is defined
              - ((VAR_NEC_WIN_update_AU.automaticMaintenanceEnabled is none) or (VAR_NEC_WIN_update_AU.automaticMaintenanceEnabled == "")
                or (not VAR_NEC_WIN_update_AU.automaticMaintenanceEnabled.strip().upper() in AVAILABLE_SWITCH_LIST))

          - name: check AUOptions
            fail:
                msg: AUOptions' value is unavailable
            when:
              - VAR_NEC_WIN_update_AU.AUOptions is defined
              - ((not VAR_NEC_WIN_update_AU.AUOptions is number) or (VAR_NEC_WIN_update_AU.AUOptions < 2) or (VAR_NEC_WIN_update_AU.AUOptions > 5))

          - name: check scheduledInstallDay
            fail:
                msg: scheduledInstallDay' value is unavailable
            when:
              - VAR_NEC_WIN_update_AU.scheduledInstallDay is defined
              - ((not VAR_NEC_WIN_update_AU.scheduledInstallDay is number) or (VAR_NEC_WIN_update_AU.scheduledInstallDay < 0) or (VAR_NEC_WIN_update_AU.scheduledInstallDay > 7))

          - name: check scheduledInstallTime
            fail:
                msg: scheduledInstallTime' value is unavailable
            when:
              - VAR_NEC_WIN_update_AU.scheduledInstallTime is defined
              - ((not VAR_NEC_WIN_update_AU.scheduledInstallTime is number) or (VAR_NEC_WIN_update_AU.scheduledInstallTime < 0) or (VAR_NEC_WIN_update_AU.scheduledInstallTime > 23))

          - name: check allowMUUpdateService
            fail:
                msg: allowMUUpdateService' value is unavailable
            when:
              - VAR_NEC_WIN_update_AU.allowMUUpdateService is defined
              - ((VAR_NEC_WIN_update_AU.allowMUUpdateService is none) or (VAR_NEC_WIN_update_AU.allowMUUpdateService == "")
                or (not VAR_NEC_WIN_update_AU.allowMUUpdateService.strip().upper() in AVAILABLE_SWITCH_LIST))
        when:
          - VAR_NEC_WIN_update_AU.status.strip().upper() == "ENABLED"
    when:
      - VAR_NEC_WIN_update_AU is defined
      - VAR_NEC_WIN_update_AU is not none
      - VAR_NEC_WIN_update_AU != ""

  - name: check whether VAR_NEC_WIN_update_WU is legal or not
    block:
      - name: check whether status is legal or not
        fail:
            msg: status' value is unavailable
        when:
          - VAR_NEC_WIN_update_WU.status is defined
          - ((VAR_NEC_WIN_update_WU.status is none) or (VAR_NEC_WIN_update_WU.status == "")
            or (not VAR_NEC_WIN_update_WU.status.strip().upper() in AVAILABLE_STATUS_LIST))

      - name: check other items of VAR_NEC_WIN_update_WU when status is ENABLED
        block:
          # - name: check WUServer
            # fail:
                # msg: WUServer' value is unavailable
            # when:
              # - VAR_NEC_WIN_update_WU.WUServer is defined
              # - ((VAR_NEC_WIN_update_WU.WUServer is none) or (VAR_NEC_WIN_update_WU.WUServer == ""))
          # - name: check WUStatusServer
            # fail:
                # msg: WUStatusServer' value is unavailable
            # when:
              # - VAR_NEC_WIN_update_WU.WUStatusServer is defined
              # - ((VAR_NEC_WIN_update_WU.WUStatusServer is none) or (VAR_NEC_WIN_update_WU.WUStatusServer == ""))
          - name: check WUServer
            fail:
              msg: "Parameter 'VAR_NEC_WIN_update_WU.WUServer' should be defined and cannot be NULL."
            when: (VAR_NEC_WIN_update_WU.WUServer is undefined) or (VAR_NEC_WIN_update_WU.WUServer is none) or (VAR_NEC_WIN_update_WU.WUServer == "")

          - name: check WUStatusServer
            fail:
              msg: "Parameter 'VAR_NEC_WIN_update_WU.WUStatusServer' should be defined and cannot be NULL."
            when: (VAR_NEC_WIN_update_WU.WUStatusServer is undefined) or (VAR_NEC_WIN_update_WU.WUStatusServer is none) or (VAR_NEC_WIN_update_WU.WUStatusServer == "")
        when:
          - VAR_NEC_WIN_update_WU.status.strip().upper() == "ENABLED"
    when:
      - VAR_NEC_WIN_update_WU is defined
      - VAR_NEC_WIN_update_WU is not none
      - VAR_NEC_WIN_update_WU != ""

  - name: check whether VAR_NEC_WIN_update_targetGroup is legal or not
    block:
      - name: check whether status is legal or not
        fail:
            msg: status' value is unavailable
        when:
          - VAR_NEC_WIN_update_targetGroup.status is defined
          - ((VAR_NEC_WIN_update_targetGroup.status is none) or (VAR_NEC_WIN_update_targetGroup.status == "")
            or (not VAR_NEC_WIN_update_targetGroup.status.strip().upper() in AVAILABLE_STATUS_LIST))

      - name: check other items of VAR_NEC_WIN_update_targetGroup when status is ENABLED
        block:
          - name: check targetGroup
            fail:
                msg: targetGroup' value is unavailable
            when:
              - VAR_NEC_WIN_update_targetGroup.targetGroup is defined
              - ((VAR_NEC_WIN_update_targetGroup.targetGroup is none) or (VAR_NEC_WIN_update_targetGroup.targetGroup == ""))
        when:
          - VAR_NEC_WIN_update_targetGroup.status.strip().upper() == "ENABLED"
    when:
      - VAR_NEC_WIN_update_targetGroup is defined
      - VAR_NEC_WIN_update_targetGroup is not none
      - VAR_NEC_WIN_update_targetGroup != ""
